### ISSUE TITLE
kindel时间显示出错

### ISSUE THREAD

**Issue by xfangfang** [NodeWee/LessClock#1]
在我的kindle7上显示时间为格林威治时间，而不是北京时间

**Comment by NodeWee** [comment]
收到。等有空我来看看

**Comment by xfangfang** [comment]
@NodeWee 
抱歉 不知道为什么邮箱没有给我发送通知，辛苦啦。
我是用的是kindle 7代，目前问题仍旧存在。
且我设置的系统语言是英语，但是显示仍为汉语，看起来kindle上的浏览器有点与众不同

**Comment by NodeWee** [comment]
1，语言问题是个 bug，已修复。
2，时区问题，我没有设备无法重现。临时解决方案：添加了一个可以手动设置时间偏移量的选项

谢谢你的反馈 👍

**Comment by xfangfang** [comment]
非常棒 都已经好用啦 感谢感谢
